CREATE TABLE TRADER 
(TRADER_ID      STRING PK NOT NULL,
TICKER			STRING PK NOT NULL,
NUMBER_OWNED	INT);

CREATE TABLE TRADER_PERFORMANCE
(TRADER_ID				STRING PK NOT NULL,
MEASURE_DATE			DATE,
ACCOUNT_VALUE			NUMBER);

CREATE TABLE TRADER_PROPERTIES
(TRADER_ID 		STRING PK NOT NULL,
TRADER_TYPE 	STRING NOT NULL,
PE 				NUMBER,
EBITDA 			NUMBER,
TICKER_TREND 	NUMBER,
SHORT_RATIO 	NUMBER,
RANDOM_P		NUMBER,
BALANCE 		NUMBER NOT NULL);